name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate Deployment
        run: |
          echo "Starting simulated deployment..."
          sleep 5  # Simulate deployment delay
          echo "Deployment completed successfully!"
