name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          username: ${{ secrets.SERVER_USERNAME }}
          script: |
            echo "Deployment starting..."

            # Navigate to project directory
            if [ ! -d "fastapi-book-project" ]; then
              git clone https://github.com/davidumoru/fastapi-book-project.git
            fi
            cd fastapi-book-project
            git reset --hard origin/main
            git pull origin main

            # Create virtual environment if it doesn't exist
            if [ ! -d "venv" ]; then
              python3 -m venv venv || exit 1
            fi

            # Activate virtual environment and install dependencies
            source venv/bin/activate || . venv/bin/activate
            python -m pip install --upgrade pip || exit 1
            pip install --upgrade -r requirements.txt || exit 1

            # Stop existing application if running
            if pgrep -x "uvicorn" > /dev/null; then
              echo "Stopping existing application..."
              killall uvicorn || exit 1
              echo "Application stopped successfully"
            else
              echo "No existing application running"
            fi

            # Start the application
            echo "Starting application..."
            nohup uvicorn main:app --host 0.0.0.0 --port 8000 > app.log 2>&1 &
            echo "Application started successfully"

            # Tail logs
            tail -f app.log
